### ISSUE TITLE
pricing:* needs to be in the not_actions when limiting regions

### ISSUE THREAD

**Issue by ricbartm** [trussworks/terraform-aws-ou-scp#22]
We have identified the AWS Console shows some errors since we moved a Sandbox AWS account to a new AWS Organization where we are implementing AWS Organization SCPs.

![image](https://user-images.githubusercontent.com/4131130/119811405-58b65800-bee7-11eb-8b13-ae3831201234.png)

The OU is using this configuration:
```
module "aws_org_scp_ou_sandbox" {
  source    = "trussworks/ou-scp/aws"
  version   = "~> 1.4.0"

  target    = aws_organizations_organizational_unit.sandbox

  deny_leaving_orgs             = true
  deny_root_account             = true
  protect_iam_roles             = true
  protect_iam_role_resources    = [
    "arn:aws:iam::*:role/OrganizationAccountAccessRole"
  ]
  limit_regions                 = true
  allowed_regions               = ["us-east-2"]
  require_s3_encryption = true

}

```

Looks like the Pricing API is not a regional service so far and it's only available in `us-east-1` and `ap-south-1`. For this reason, like it happens with IAM or Organizations, should not be restricted as part of the SCPs.
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-pelong.html (see `Service endpoint`)

We are willing to send the PR upstream as soon as our time allows

**Comment by cblkwell** [comment]
This change has been incorporated into v1.5.0, which is now available on the registry: https://registry.terraform.io/modules/trussworks/ou-scp/aws/latest
