### ISSUE TITLE
Enforcing AWS S3 SSE

### ISSUE THREAD

**Issue by ricbartm** [trussworks/terraform-aws-ou-scp#24]
Hello,

We are using this Terraform module in order to enforce AWS SSE encryption in the org and we found an unexpected behaviour we would like to share with you.

We created an AWS S3 bucket with default AWS SSE using Amazon key (AWS-SSE). We also enabled `require_s3_encryption = true` and as result the following policy was added:
```json
{
      "Sid": "DenyIncorrectEncryptionHeader",
      "Effect": "Deny",
      "Action": "s3:PutObject",
      "Resource": "*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": [
            "AES256",
            "aws:kms"
          ]
        }
      }
    },
    {
      "Sid": "DenyUnEncryptedObjectUploads",
      "Effect": "Deny",
      "Action": "s3:PutObject",
      "Resource": "*",
      "Condition": {
        "Null": {
          "s3:x-amz-server-side-encryption": [
            "true"
          ]
        }
      }
```

Our surprise is that a third party software that we run in AWS, as well as AWS CLI `s3:PutObject` operations, were failing.

The expected behaviour (our expected behaviour) was that given that the target AWS S3 bucket already has default AWS SSE enabled, the PutObject operations would succeed and would be allowed by the policy. Unfortunately, they are blocked.

We have been thinking on disabling this SCP, and instead, deny abt `s3:CreateObject` that does not have the correct setting of AWS SSE enabled. Unfortunately, this could be disabled afterwards, unless explicitely denied 🤷 .

What is your recommendation on the best and more resilient practices, especially when third-party software writes into S3 and we depend on the vendor to adapt the code to enable AWS SSE?

**Comment by avanti-joshi** [comment]
@ricbartm is this still an issue you are having? how are you accessing the s3 bucket with the AWS CLI? Could you provide an output from the CLI? The policy the module creates requires the sse flag to be set for access - https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html!
